/* Generated by itemis CREATE code generator. */


#include "sc_types.h"

#include "Statechart.h"
#include "Statechart_required.h"

/*! \file
Implementation of the state machine 'Statechart'
*/

#ifndef SC_UNUSED
#define SC_UNUSED(P) (void)(P)
#endif

/* prototypes of all internal functions */
static void enact_main_region_recto(Statechart* handle);
static void enact_main_region_girarDer(Statechart* handle);
static void enact_main_region_girarIzq(Statechart* handle);
static void enact_main_region_retroceso(Statechart* handle);
static void enseq_main_region_recto_default(Statechart* handle);
static void enseq_main_region_girarDer_default(Statechart* handle);
static void enseq_main_region_girarIzq_default(Statechart* handle);
static void enseq_main_region_retroceso_default(Statechart* handle);
static void enseq_main_region_default(Statechart* handle);
static void exseq_main_region_recto(Statechart* handle);
static void exseq_main_region_girarDer(Statechart* handle);
static void exseq_main_region_girarIzq(Statechart* handle);
static void exseq_main_region_retroceso(Statechart* handle);
static void exseq_main_region(Statechart* handle);
static void react_main_region__entry_Default(Statechart* handle);

/*! The reactions of state recto. */
static sc_integer main_region_recto_react(Statechart* handle, const sc_integer transitioned_before);

/*! The reactions of state girarDer. */
static sc_integer main_region_girarDer_react(Statechart* handle, const sc_integer transitioned_before);

/*! The reactions of state girarIzq. */
static sc_integer main_region_girarIzq_react(Statechart* handle, const sc_integer transitioned_before);

/*! The reactions of state retroceso. */
static sc_integer main_region_retroceso_react(Statechart* handle, const sc_integer transitioned_before);


static void clear_in_events(Statechart* handle);

static void micro_step(Statechart* handle);

/*! Performs a 'run to completion' step. */
static void run_cycle(Statechart* handle);






static void statechart_eventqueue_init(statechart_eventqueue * eq, statechart_event *buffer, sc_integer capacity);
static sc_integer statechart_eventqueue_size(statechart_eventqueue * eq);
static void statechart_event_init(statechart_event * ev, StatechartEventID name);
static statechart_event statechart_eventqueue_pop(statechart_eventqueue * eq);
static sc_boolean statechart_eventqueue_push(statechart_eventqueue * eq, statechart_event ev);
static void statechart_add_event_to_queue(statechart_eventqueue * eq, StatechartEventID name);
static sc_boolean statechart_dispatch_event(Statechart* handle, const statechart_event * event);
static statechart_event statechart_get_next_event(Statechart* handle);
static sc_boolean statechart_dispatch_next_event(Statechart* handle);


void statechart_init(Statechart* handle)
{
	sc_integer i;
	
	for (i = 0; i < STATECHART_MAX_ORTHOGONAL_STATES; ++i)
	{
		handle->stateConfVector[i] = Statechart_last_state;
	}
	
				
	clear_in_events(handle);
	
	
	
	handle->isExecuting = bool_false;
	statechart_eventqueue_init(&handle->in_event_queue, handle->in_buffer, STATECHART_IN_EVENTQUEUE_BUFFERSIZE);
}

void statechart_enter(Statechart* handle)
{
	/* Activates the state machine. */
	if (handle->isExecuting == bool_true)
	{ 
		return;
	} 
	handle->isExecuting = bool_true;
	/* Default enter sequence for statechart Statechart */
	enseq_main_region_default(handle);
	handle->isExecuting = bool_false;
}

void statechart_exit(Statechart* handle)
{
	/* Deactivates the state machine. */
	if (handle->isExecuting == bool_true)
	{ 
		return;
	} 
	handle->isExecuting = bool_true;
	/* Default exit sequence for statechart Statechart */
	exseq_main_region(handle);
	handle->stateConfVector[0] = Statechart_last_state;
	handle->isExecuting = bool_false;
}

/*!
Can be used by the client code to trigger a run to completion step without raising an event.
*/
void statechart_trigger_without_event(Statechart* handle) {
	run_cycle(handle);
}


sc_boolean statechart_is_active(const Statechart* handle)
{
	sc_boolean result = bool_false;
	sc_integer i;
	
	for(i = 0; i < STATECHART_MAX_ORTHOGONAL_STATES; i++)
	{
		result = result || handle->stateConfVector[i] != Statechart_last_state;
	}
	
	return result;
}

/* 
 * Always returns 'false' since this state machine can never become final.
 */
sc_boolean statechart_is_final(const Statechart* handle)
{
	SC_UNUSED(handle);
	return bool_false;
}

sc_boolean statechart_is_state_active(const Statechart* handle, StatechartStates state)
{
	sc_boolean result = bool_false;
	switch (state)
	{
		case Statechart_main_region_recto :
			result = (sc_boolean) (handle->stateConfVector[SCVI_STATECHART_MAIN_REGION_RECTO] == Statechart_main_region_recto
			);
				break;
		case Statechart_main_region_girarDer :
			result = (sc_boolean) (handle->stateConfVector[SCVI_STATECHART_MAIN_REGION_GIRARDER] == Statechart_main_region_girarDer
			);
				break;
		case Statechart_main_region_girarIzq :
			result = (sc_boolean) (handle->stateConfVector[SCVI_STATECHART_MAIN_REGION_GIRARIZQ] == Statechart_main_region_girarIzq
			);
				break;
		case Statechart_main_region_retroceso :
			result = (sc_boolean) (handle->stateConfVector[SCVI_STATECHART_MAIN_REGION_RETROCESO] == Statechart_main_region_retroceso
			);
				break;
			default:
				result = bool_false;
				break;
		}
		return result;
	}

static void clear_in_events(Statechart* handle)
{
	handle->iface.sensorIzqON_raised = bool_false;
	handle->iface.sensorIzqOFF_raised = bool_false;
	handle->iface.sensorDerON_raised = bool_false;
	handle->iface.sensorDerOFF_raised = bool_false;
	handle->iface.ambosSensoresOFF_raised = bool_false;
	handle->iface.ambosSensoresON_raised = bool_false;
}

static void micro_step(Statechart* handle)
{
	switch(handle->stateConfVector[ 0 ])
	{
		case Statechart_main_region_recto :
		{
			main_region_recto_react(handle,-1);
			break;
		}
		case Statechart_main_region_girarDer :
		{
			main_region_girarDer_react(handle,-1);
			break;
		}
		case Statechart_main_region_girarIzq :
		{
			main_region_girarIzq_react(handle,-1);
			break;
		}
		case Statechart_main_region_retroceso :
		{
			main_region_retroceso_react(handle,-1);
			break;
		}
		default: 
			/* do nothing */
			break;
	}
}

static void run_cycle(Statechart* handle)
{
	/* Performs a 'run to completion' step. */
	if (handle->isExecuting == bool_true)
	{ 
		return;
	} 
	handle->isExecuting = bool_true;
	statechart_dispatch_next_event(handle);
	do
	{ 
		micro_step(handle);
		clear_in_events(handle);
	} while (statechart_dispatch_next_event(handle) == bool_true);
	handle->isExecuting = bool_false;
}


void statechart_raise_sensorIzqON(Statechart* handle)
{
	statechart_add_event_to_queue(&(handle->in_event_queue), Statechart_sensorIzqON);
	run_cycle(handle);
}

void statechart_raise_sensorIzqOFF(Statechart* handle)
{
	statechart_add_event_to_queue(&(handle->in_event_queue), Statechart_sensorIzqOFF);
	run_cycle(handle);
}

void statechart_raise_sensorDerON(Statechart* handle)
{
	statechart_add_event_to_queue(&(handle->in_event_queue), Statechart_sensorDerON);
	run_cycle(handle);
}

void statechart_raise_sensorDerOFF(Statechart* handle)
{
	statechart_add_event_to_queue(&(handle->in_event_queue), Statechart_sensorDerOFF);
	run_cycle(handle);
}

void statechart_raise_ambosSensoresOFF(Statechart* handle)
{
	statechart_add_event_to_queue(&(handle->in_event_queue), Statechart_ambosSensoresOFF);
	run_cycle(handle);
}

void statechart_raise_ambosSensoresON(Statechart* handle)
{
	statechart_add_event_to_queue(&(handle->in_event_queue), Statechart_ambosSensoresON);
	run_cycle(handle);
}






/* implementations of all internal functions */

/* Entry action for state 'recto'. */
static void enact_main_region_recto(Statechart* handle)
{
	/* Entry action for state 'recto'. */
	statechart_arrancar(handle);
	statechart_recto(handle);
}

/* Entry action for state 'girarDer'. */
static void enact_main_region_girarDer(Statechart* handle)
{
	/* Entry action for state 'girarDer'. */
	statechart_frenar(handle);
	statechart_girarDer(handle);
}

/* Entry action for state 'girarIzq'. */
static void enact_main_region_girarIzq(Statechart* handle)
{
	/* Entry action for state 'girarIzq'. */
	statechart_frenar(handle);
	statechart_girarIzq(handle);
}

/* Entry action for state 'retroceso'. */
static void enact_main_region_retroceso(Statechart* handle)
{
	/* Entry action for state 'retroceso'. */
	statechart_retroceso(handle);
}

/* 'default' enter sequence for state recto */
static void enseq_main_region_recto_default(Statechart* handle)
{
	/* 'default' enter sequence for state recto */
	enact_main_region_recto(handle);
	handle->stateConfVector[0] = Statechart_main_region_recto;
}

/* 'default' enter sequence for state girarDer */
static void enseq_main_region_girarDer_default(Statechart* handle)
{
	/* 'default' enter sequence for state girarDer */
	enact_main_region_girarDer(handle);
	handle->stateConfVector[0] = Statechart_main_region_girarDer;
}

/* 'default' enter sequence for state girarIzq */
static void enseq_main_region_girarIzq_default(Statechart* handle)
{
	/* 'default' enter sequence for state girarIzq */
	enact_main_region_girarIzq(handle);
	handle->stateConfVector[0] = Statechart_main_region_girarIzq;
}

/* 'default' enter sequence for state retroceso */
static void enseq_main_region_retroceso_default(Statechart* handle)
{
	/* 'default' enter sequence for state retroceso */
	enact_main_region_retroceso(handle);
	handle->stateConfVector[0] = Statechart_main_region_retroceso;
}

/* 'default' enter sequence for region main region */
static void enseq_main_region_default(Statechart* handle)
{
	/* 'default' enter sequence for region main region */
	react_main_region__entry_Default(handle);
}

/* Default exit sequence for state recto */
static void exseq_main_region_recto(Statechart* handle)
{
	/* Default exit sequence for state recto */
	handle->stateConfVector[0] = Statechart_last_state;
}

/* Default exit sequence for state girarDer */
static void exseq_main_region_girarDer(Statechart* handle)
{
	/* Default exit sequence for state girarDer */
	handle->stateConfVector[0] = Statechart_last_state;
}

/* Default exit sequence for state girarIzq */
static void exseq_main_region_girarIzq(Statechart* handle)
{
	/* Default exit sequence for state girarIzq */
	handle->stateConfVector[0] = Statechart_last_state;
}

/* Default exit sequence for state retroceso */
static void exseq_main_region_retroceso(Statechart* handle)
{
	/* Default exit sequence for state retroceso */
	handle->stateConfVector[0] = Statechart_last_state;
}

/* Default exit sequence for region main region */
static void exseq_main_region(Statechart* handle)
{
	/* Default exit sequence for region main region */
	/* Handle exit of all possible states (of Statechart.main_region) at position 0... */
	switch(handle->stateConfVector[ 0 ])
	{
		case Statechart_main_region_recto :
		{
			exseq_main_region_recto(handle);
			break;
		}
		case Statechart_main_region_girarDer :
		{
			exseq_main_region_girarDer(handle);
			break;
		}
		case Statechart_main_region_girarIzq :
		{
			exseq_main_region_girarIzq(handle);
			break;
		}
		case Statechart_main_region_retroceso :
		{
			exseq_main_region_retroceso(handle);
			break;
		}
		default: 
			/* do nothing */
			break;
	}
}

/* Default react sequence for initial entry  */
static void react_main_region__entry_Default(Statechart* handle)
{
	/* Default react sequence for initial entry  */
	enseq_main_region_recto_default(handle);
}


static sc_integer main_region_recto_react(Statechart* handle, const sc_integer transitioned_before)
{
	/* The reactions of state recto. */
 			sc_integer transitioned_after = transitioned_before;
	if ((transitioned_after) < (0))
	{ 
		if (handle->iface.sensorIzqON_raised == bool_true)
		{ 
			exseq_main_region_recto(handle);
			enseq_main_region_girarDer_default(handle);
			transitioned_after = 0;
		}  else
		{
			if (handle->iface.sensorDerON_raised == bool_true)
			{ 
				exseq_main_region_recto(handle);
				enseq_main_region_girarIzq_default(handle);
				transitioned_after = 0;
			}  else
			{
				if (handle->iface.ambosSensoresON_raised == bool_true)
				{ 
					exseq_main_region_recto(handle);
					enseq_main_region_retroceso_default(handle);
					transitioned_after = 0;
				} 
			}
		}
	} 
	/* If no transition was taken */
	if ((transitioned_after) == (transitioned_before))
	{ 
		/* then execute local reactions. */
		transitioned_after = transitioned_before;
	} 
	return transitioned_after;
}

static sc_integer main_region_girarDer_react(Statechart* handle, const sc_integer transitioned_before)
{
	/* The reactions of state girarDer. */
 			sc_integer transitioned_after = transitioned_before;
	if ((transitioned_after) < (0))
	{ 
		if (handle->iface.sensorIzqOFF_raised == bool_true)
		{ 
			exseq_main_region_girarDer(handle);
			enseq_main_region_recto_default(handle);
			transitioned_after = 0;
		} 
	} 
	/* If no transition was taken */
	if ((transitioned_after) == (transitioned_before))
	{ 
		/* then execute local reactions. */
		transitioned_after = transitioned_before;
	} 
	return transitioned_after;
}

static sc_integer main_region_girarIzq_react(Statechart* handle, const sc_integer transitioned_before)
{
	/* The reactions of state girarIzq. */
 			sc_integer transitioned_after = transitioned_before;
	if ((transitioned_after) < (0))
	{ 
		if (handle->iface.sensorDerOFF_raised == bool_true)
		{ 
			exseq_main_region_girarIzq(handle);
			enseq_main_region_recto_default(handle);
			transitioned_after = 0;
		} 
	} 
	/* If no transition was taken */
	if ((transitioned_after) == (transitioned_before))
	{ 
		/* then execute local reactions. */
		transitioned_after = transitioned_before;
	} 
	return transitioned_after;
}

static sc_integer main_region_retroceso_react(Statechart* handle, const sc_integer transitioned_before)
{
	/* The reactions of state retroceso. */
 			sc_integer transitioned_after = transitioned_before;
	if ((transitioned_after) < (0))
	{ 
		if (handle->iface.ambosSensoresOFF_raised == bool_true)
		{ 
			exseq_main_region_retroceso(handle);
			enseq_main_region_recto_default(handle);
			transitioned_after = 0;
		} 
	} 
	/* If no transition was taken */
	if ((transitioned_after) == (transitioned_before))
	{ 
		/* then execute local reactions. */
		transitioned_after = transitioned_before;
	} 
	return transitioned_after;
}




static void statechart_eventqueue_init(statechart_eventqueue * eq, statechart_event *buffer, sc_integer capacity)
{
	eq->events = buffer;
	eq->capacity = capacity;
	eq->push_index = 0;
	eq->pop_index = 0;
	eq->size = 0;
}

static sc_integer statechart_eventqueue_size(statechart_eventqueue * eq)
{
	return eq->size;
}

static statechart_event statechart_eventqueue_pop(statechart_eventqueue * eq)
{
	statechart_event event;
	if(statechart_eventqueue_size(eq) <= 0) {
		statechart_event_init(&event, Statechart_invalid_event);
	}
	else {
		event = eq->events[eq->pop_index];
		
		if(eq->pop_index < eq->capacity - 1) {
			eq->pop_index++;
		} 
		else {
			eq->pop_index = 0;
		}
		eq->size--;
	}
	return event;
}
static sc_boolean statechart_eventqueue_push(statechart_eventqueue * eq, statechart_event ev)
{
	if(statechart_eventqueue_size(eq) == eq->capacity) {
		return bool_false;
	}
	else {
		eq->events[eq->push_index] = ev;
		
		if(eq->push_index < eq->capacity - 1) {
			eq->push_index++;
		}
		else {
			eq->push_index = 0;
		}
		eq->size++;
		
		return bool_true;
	}
}
static void statechart_event_init(statechart_event * ev, StatechartEventID name)
{
	ev->name = name;
}

static void statechart_add_event_to_queue(statechart_eventqueue * eq, StatechartEventID name)
{
	statechart_event event;
	statechart_event_init(&event, name);
	statechart_eventqueue_push(eq, event);
}

static sc_boolean statechart_dispatch_event(Statechart* handle, const statechart_event * event) {
	switch(event->name) {
		case Statechart_sensorIzqON:
		{
			handle->iface.sensorIzqON_raised = bool_true;
			return bool_true;
		}
		case Statechart_sensorIzqOFF:
		{
			handle->iface.sensorIzqOFF_raised = bool_true;
			return bool_true;
		}
		case Statechart_sensorDerON:
		{
			handle->iface.sensorDerON_raised = bool_true;
			return bool_true;
		}
		case Statechart_sensorDerOFF:
		{
			handle->iface.sensorDerOFF_raised = bool_true;
			return bool_true;
		}
		case Statechart_ambosSensoresOFF:
		{
			handle->iface.ambosSensoresOFF_raised = bool_true;
			return bool_true;
		}
		case Statechart_ambosSensoresON:
		{
			handle->iface.ambosSensoresON_raised = bool_true;
			return bool_true;
		}
		default:
			return bool_false;
	}
}

static statechart_event statechart_get_next_event(Statechart* handle)
{
	statechart_event next_event;
	statechart_event_init(&next_event, Statechart_invalid_event);
	if(statechart_eventqueue_size(&(handle->in_event_queue)) > 0) {
		next_event = statechart_eventqueue_pop(&(handle->in_event_queue));
	}
	return next_event;
}

static sc_boolean statechart_dispatch_next_event(Statechart* handle)
{
	statechart_event nextEvent;
	nextEvent = statechart_get_next_event(handle);
	return statechart_dispatch_event(handle, &nextEvent);
}
