/* Generated by itemis CREATE code generator. */

#ifndef STATECHART_REQUIRED_H_
#define STATECHART_REQUIRED_H_

#include "sc_types.h"
#include "Statechart.h"

#ifdef __cplusplus
extern "C"
{
#endif 

/*! \file
This header defines prototypes for all functions that are required by the state machine implementation.

This state machine makes use of operations declared in the state machines interface or internal scopes. Thus the function prototypes:
- statechart_girarDer
- statechart_girarIzq
- statechart_recto
- statechart_arrancar
- statechart_bajarVelocidad
- statechart_frenar
- statechart_retroceso
are defined.

These functions will be called during a 'run to completion step' (runCycle) of the statechart. 
There are some constraints that have to be considered for the implementation of these functions:
- make sure that the execution time is as short as possible.
*/
extern void statechart_girarDer( Statechart* handle);
extern void statechart_girarIzq( Statechart* handle);
extern void statechart_recto( Statechart* handle);
extern void statechart_arrancar( Statechart* handle);
extern void statechart_bajarVelocidad( Statechart* handle);
extern void statechart_frenar( Statechart* handle);
extern void statechart_retroceso( Statechart* handle);




#ifdef __cplusplus
}
#endif 

#endif /* STATECHART_REQUIRED_H_ */
